#!/usr/bin/env node
/**
 * AWS → Elastic Custom Dashboard Installer
 *
 * Interactive CLI that installs Kibana dashboards for AWS Glue and SageMaker
 * data generated by the AWS → Elastic Load Generator.
 *
 * Run with:  node index.mjs
 *            npm run setup:dashboards
 *
 * No external dependencies — uses Node.js built-ins only.
 * Requires Kibana 9.4+ (Elastic-Api-Version: 1 dashboards API).
 */

import readline from "readline";
import { readFileSync, readdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ─── Helpers ─────────────────────────────────────────────────────────────────

function createReadline() {
  return readline.createInterface({ input: process.stdin, output: process.stdout });
}

function prompt(rl, question) {
  return new Promise((resolve) => rl.question(question, (a) => resolve(a.trim())));
}

function printHeader() {
  console.log("");
  console.log("╔══════════════════════════════════════════════════════╗");
  console.log("║     AWS → Elastic Custom Dashboard Installer         ║");
  console.log("╚══════════════════════════════════════════════════════╝");
  console.log("");
  console.log("Installs Kibana dashboards for AWS services monitored");
  console.log("by the AWS → Elastic Load Generator.");
  console.log("");
}

// ─── Deployment type ─────────────────────────────────────────────────────────

const DEPLOYMENT_TYPES = [
  { id: "self-managed", label: "Self-Managed  (on-premises, Docker, VM)" },
  { id: "cloud-hosted", label: "Elastic Cloud Hosted  (cloud.elastic.co)" },
  { id: "serverless",   label: "Elastic Serverless  (cloud.elastic.co/serverless)" },
];

async function promptDeploymentType(rl) {
  console.log("Select your Elastic deployment type:");
  console.log("");
  DEPLOYMENT_TYPES.forEach(({ label }, i) => console.log(`  ${i + 1}. ${label}`));
  console.log("");

  while (true) {
    const input = await prompt(rl, "Enter 1, 2, or 3:\n> ");
    const idx = parseInt(input, 10) - 1;
    if (idx >= 0 && idx < DEPLOYMENT_TYPES.length) return DEPLOYMENT_TYPES[idx].id;
    console.error("  Please enter 1, 2, or 3.");
  }
}

function getUrlExample(deploymentType) {
  if (deploymentType === "self-managed")
    return "http://localhost:5601  or  https://kibana.yourdomain.internal:5601";
  if (deploymentType === "serverless")
    return "https://my-deployment.kb.eu-west-2.aws.elastic.cloud";
  return "https://my-deployment.kb.us-east-1.aws.elastic-cloud.com:9243";
}

async function maybeSKipTls(rl, deploymentType) {
  if (deploymentType !== "self-managed") return;

  const answer = await prompt(
    rl,
    "Skip TLS certificate verification? Required for self-signed / internal CA certs. (y/N):\n> "
  );
  if (answer.toLowerCase() === "y" || answer.toLowerCase() === "yes") {
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
    console.log("  ⚠  TLS verification disabled — ensure you trust this endpoint.");
  }
  console.log("");
}

// ─── Dashboard discovery ─────────────────────────────────────────────────────

function loadDashboards() {
  const files = readdirSync(__dirname).filter((f) => f.endsWith("-dashboard.json"));
  return files.map((file) => {
    const def = JSON.parse(readFileSync(join(__dirname, file), "utf-8"));
    return { file, title: def.title, definition: def };
  });
}

// ─── Kibana client ───────────────────────────────────────────────────────────

function createKibanaClient(baseUrl, apiKey, deploymentType) {
  const base = baseUrl.replace(/\/$/, "");
  const headers = {
    "Content-Type": "application/json",
    "kbn-xsrf": "true",
    Authorization: `ApiKey ${apiKey}`,
  };

  async function request(method, path, body, extraHeaders = {}) {
    const res = await fetch(`${base}${path}`, {
      method,
      headers: { ...headers, ...extraHeaders },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });

    if (res.status === 404) return null;

    if (!res.ok) {
      let text;
      try { text = await res.text(); } catch { text = "(unable to read response)"; }
      throw new Error(`Kibana request failed: ${method} ${path} → HTTP ${res.status}\n${text}`);
    }

    return res.json();
  }

  return {
    async testConnection() {
      return request("GET", "/api/status");
    },

    /**
     * Search for an existing dashboard by title.
     * Returns null on Serverless (Saved Objects API is unavailable there),
     * allowing installation to proceed without an idempotency check.
     */
    async findDashboardByTitle(title) {
      if (deploymentType === "serverless") return null;

      const encoded = encodeURIComponent(title);
      try {
        const result = await request(
          "GET",
          `/api/saved_objects/_find?type=dashboard&search_fields=title&search=${encoded}&per_page=10`
        );
        if (!result?.saved_objects) return null;
        return result.saved_objects.find(
          (obj) => obj.attributes?.title === title
        ) ?? null;
      } catch (err) {
        // Saved Objects API unavailable (e.g. Serverless) — skip the check
        if (err.message.includes("HTTP 400")) return null;
        throw err;
      }
    },

    async createDashboard(definition) {
      const { id, spaces, ...body } = definition;
      return request("POST", "/api/dashboards", body, {
        "Elastic-Api-Version": "1",
      });
    },
  };
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  printHeader();

  const dashboards = loadDashboards();

  if (dashboards.length === 0) {
    console.log("No dashboard JSON files found in this directory. Exiting.");
    process.exit(0);
  }

  const rl = createReadline();

  // 1. Deployment type
  const deploymentType = await promptDeploymentType(rl);
  console.log("");

  // 2. TLS (self-managed only)
  await maybeSKipTls(rl, deploymentType);

  // 3. Kibana URL
  const kibanaUrl = await prompt(
    rl,
    `Kibana URL (e.g. ${getUrlExample(deploymentType)}):\n> `
  );

  if (!kibanaUrl) {
    console.error("No URL provided. Exiting.");
    rl.close();
    process.exit(1);
  }

  if (deploymentType === "self-managed") {
    if (!kibanaUrl.startsWith("http://") && !kibanaUrl.startsWith("https://")) {
      console.error("URL must start with http:// or https://. Exiting.");
      rl.close();
      process.exit(1);
    }
  } else {
    if (!kibanaUrl.startsWith("https://")) {
      console.error("URL must start with https://. Exiting.");
      rl.close();
      process.exit(1);
    }
  }

  // 4. API Key
  const apiKey = await prompt(rl, "\nElastic API Key:\n> ");

  if (!apiKey) {
    console.error("No API key provided. Exiting.");
    rl.close();
    process.exit(1);
  }

  // 5. Test connection
  console.log("\nTesting connection...");
  const client = createKibanaClient(kibanaUrl, apiKey, deploymentType);

  try {
    const status = await client.testConnection();
    const version = status?.version?.number ?? "";
    const name = status?.name ?? "(unknown)";
    console.log(`  Connected to Kibana: ${name}${version ? ` (${version})` : ""}`);
  } catch (err) {
    console.error(`  Connection failed: ${err.message}`);
    rl.close();
    process.exit(1);
  }

  if (deploymentType === "serverless") {
    console.log("  ℹ  Serverless: duplicate-check unavailable — re-running will create additional copies of already-installed dashboards.");
  }

  // 6. Dashboard selection menu
  console.log("\nAvailable dashboards:\n");
  dashboards.forEach((d, i) => {
    console.log(`  ${i + 1}. ${d.title}`);
  });
  const allIndex = dashboards.length + 1;
  console.log(`  ${allIndex}. all  (install every dashboard)`);
  console.log("");

  const selectionInput = await prompt(rl, `Enter number(s) comma-separated, or "all":\n> `);
  rl.close();

  // Parse selection
  let selected = [];

  if (selectionInput.toLowerCase() === "all") {
    selected = dashboards;
  } else {
    const tokens = selectionInput.split(",").map((s) => s.trim()).filter(Boolean);
    const seen = new Set();
    for (const token of tokens) {
      const num = parseInt(token, 10);
      if (isNaN(num) || num < 1 || num > allIndex) {
        console.warn(`  Warning: invalid selection "${token}" — skipping.`);
        continue;
      }
      if (num === allIndex) {
        selected = dashboards;
        break;
      }
      const d = dashboards[num - 1];
      if (!seen.has(d.title)) {
        seen.add(d.title);
        selected.push(d);
      }
    }
  }

  if (selected.length === 0) {
    console.log("\nNo dashboards selected. Exiting.");
    process.exit(0);
  }

  // 7. Install dashboards
  console.log(`\nInstalling ${selected.length} dashboard(s)...\n`);

  let installedCount = 0;
  let skippedCount = 0;
  let failedCount = 0;

  for (const { title, definition } of selected) {
    try {
      const existing = await client.findDashboardByTitle(title);

      if (existing !== null) {
        console.log(`  ✓ "${title}" — already installed, skipping`);
        skippedCount++;
        continue;
      }

      const result = await client.createDashboard(definition);
      const id = result?.id ?? result?.data?.id ?? "(unknown id)";
      console.log(`  ✓ "${title}" — installed (id: ${id})`);
      installedCount++;
    } catch (err) {
      console.error(`  ✗ "${title}" — FAILED: ${err.message}`);
      failedCount++;
    }
  }

  // 8. Summary
  const total = selected.length;
  console.log("");
  console.log(
    `Installed ${installedCount} / ${total} dashboard(s).` +
      (skippedCount > 0 ? ` (${skippedCount} already installed, skipped)` : "") +
      (failedCount > 0 ? ` (${failedCount} failed)` : "")
  );

  if (failedCount > 0) {
    console.log(
      "\nNote: dashboard creation requires Kibana 9.4+ and an API key with kibana_admin privileges."
    );
  }

  console.log("Done.");
}

main().catch((err) => {
  console.error("Unexpected error:", err);
  process.exit(1);
});
